import {StyleSheet} from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'flex-start',
    alignItems: 'center',
    backgroundColor: 'white',
  },
  containerInputs: {display: 'flex', flexDirection: 'row'},
  InputType: {
    paddingHorizontal: 20,
    paddingVertical: 15,
    backgroundColor: '#fff',
    alignSelf: 'stretch',
    marginBottom: 15,
    marginHorizontal: 20,
    marginVertical: 20,
    fontSize: 16,
    width: '90%',
    borderBottomWidth: 1,
    borderBottomColor: 'gray',
  },
  Input: {
    paddingHorizontal: 20,
    paddingVertical: 15,
    backgroundColor: '#fff',
    alignSelf: 'stretch',
    marginBottom: 15,
    marginHorizontal: 20,
    marginVertical: 20,
    fontSize: 16,
    width: '40%',
    borderBottomWidth: 1,
    borderBottomColor: 'gray',
  },
  InputMini: {
    borderBottomColor: 'gray',
    width: '23.5%',
    paddingHorizontal: 10,
    paddingVertical: 15,
    borderBottomWidth: 1,
    backgroundColor: '#fff',
    alignSelf: 'stretch',
    marginBottom: 15,
    marginHorizontal: 20,
    marginVertical: 20,
    fontSize: 16,
  },
  Button: {
    position: 'relative',
    left: '65%',
    padding: 8,
    width: '30%',
    borderRadius: 5,
    backgroundColor: '#53aded',
    alignSelf: 'stretch',
    marginTop: 10,
  },
  ButtonText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 16,
    textAlign: 'center',
  },
  ErrorMessage: {
    textAlign: 'center',
    color: '#ce2029',
    fontSize: 16,
    marginBottom: 15,
    marginHorizontal: 20,
  },
});

export default styles;
